---

name: build
on:
  push:
    branches:
      - master
  pull_request:
  schedule:
    - cron: '25 4 * * 4'
  workflow_dispatch:

jobs:
  build-base:
    uses: ./.github/workflows/build-one.yml
    with:
      folder: .
      tag: latest
    secrets: inherit
